# Generated by Django 5.2.13 on 2026-04-25 05:13

from django.db import migrations


def create_test_user(apps, schema_editor):
    from django.contrib.auth.hashers import make_password
    User = apps.get_model('backend', 'User')
    
    # Create a test user if it doesn't exist
    User.objects.get_or_create(
        username='testuser',
        defaults={
            'email': 'test@example.com',
            'password': make_password('password123'),
            'name': 'Test User',
            'is_staff': True,
            'is_superuser': False,
        }
    )

def remove_test_user(apps, schema_editor):
    User = apps.get_model('backend', 'User')
    User.objects.filter(username='testuser').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_test_user, remove_test_user),
    ]
