# Generated by Django 5.2.13 on 2026-04-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_create_test_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='gen_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('done', 'Done')], default='pending', max_length=50),
        ),
    ]
