# Generated by Django 5.2.13 on 2026-04-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_song_gen_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='gen_status',
            field=models.CharField(choices=[('in-progress', 'In Progress'), ('done', 'Done')], default='in-progress', max_length=50),
        ),
    ]
