# Generated by Django 5.2.13 on 2026-04-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_song_gen_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='generation_method',
            field=models.CharField(choices=[('mock', 'Mock API (Testing)'), ('suno', 'Real Suno API')], default='mock', max_length=10),
        ),
    ]
