# Generated by Django 5.2.13 on 2026-04-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_song_generation_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='gen_status',
            field=models.CharField(choices=[('in-progress', 'In Progress'), ('done', 'Done'), ('failed', 'Failed')], default='in-progress', max_length=50),
        ),
    ]
