# Generated by Django 5.2.13 on 2026-04-25 07:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_song_audio_file_song_callback_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
