# Generated by Django 5.2.13 on 2026-04-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_sharelink_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='tags',
        ),
    ]
